- components.json
- package-lock.json
- package.json
- src/app/globals.css
- src/app/page.tsx
- src/components/ui/button.tsx
- src/lib/utils.ts
> Landing page added

- SETUP.md
> Setup guideline added

- src/app/page.tsx
- src/components/Footer.tsx
Close: #13 
The new Footer.tsx component has been created changes made to ensure no break in ui
> feat: create new Footer component

- src/app/page.tsx
- src/components/ui/Navbar.tsx
closes: - #10 
This PR refactors the code by extracting the navbar from the `Homepage` component and turning it into a separate `Navbar` component. This improves code organization, reusability, and maintainability.  
- Moved the navbar code into a new `Navbar` component.  
- Updated `Homepage` to import and use `Navbar`.  
- Ensured functionality remains unchanged.  
- Enhances modularity by separating concerns.  
- Makes the `Navbar` reusable across different pages.  
- Simplifies maintenance and future updates.  
1. Run the project locally.  
2. Verify that the navbar still displays and functions correctly.  
3. Check if there are no visual or functional regressions on the homepage.  
https://www.loom.com/share/95f56a2a864542f083905254c5252b1d?sid=0269692a-cab1-4216-922f-f01bcc8d03ec …
> NAVBAR COMPONENT

- src/app/page.tsx
- src/components/home/hero.tsx
his PR refactors the existing hero section by creating a new, reusable hero component.
Closes #14
> refac : create hero component

- src/components/Contact.tsx
This resolves issue #26.
I simply created a Contact component in the /src/components folder.
Here is what the page looks like (desktop view)
Mobile view:
> feat: created the Contact component

- src/app/privacy-policy/page.tsx
- Created a new Privacy Policy page inside src/app/privacy-policy/
- Displays the text "Privacy Policy" as requested.
- No additional routing was added, following the issue instructions.
- Implemented a simple PrivacyPolicy component.
- Temporarily displayed the component for testing and attached a screenshot.
- Manually tested by rendering the component.
- No breaking changes; the component can be used anywhere in the project.
- solved #28
> Added Privacy Policy component (#28)

- src/app/page.tsx
- src/components/technology/Technology.tsx
1.Creating a new component
.Inside the components folder, create a new file (e.g., Technology.tsx).
.Move the existing Technology section code from page.tsx to Technology.tsx.
Using the new component in page.tsx
.Import the Technology component inside page.tsx.
.Replace the original Technology section with .
resolves #31
> add technology component

- src/lib/utils.ts
Hi Paul, here’s the Figma file for the ShadowChat dark mode design. Let me know if any adjustments are needed.
https://www.figma.com/design/wFlGsl3qYAiXcgdRHshO2N/Shadowchat%3A-Landing-page-dark-mode-design?node-id=0-1&t=xqBxT6oX9RXdL8Yn-1
Resolves: #25
> Figma : Landing page dark mode design

- src/app/page.tsx
- src/components/CTASection.tsx
Moved the CTA section from page.tsx to a new component CTASection.tsx.
Improved modularity and reusability.
Ensured styles and functionality remain intact.
> Refactored CTA section into a standalone component

- src/app/contact/page.tsx
- src/components/Contact.tsx
This PR addresses issue #41: **"Migrate contact.tsx Page to New Contact Folder in App Directory"**.
The `Contact.tsx` file has been moved from the `components` folder to a new route-based structure under `app/contact/page.tsx`, following the same pattern used by existing pages like `privacy-policy` and `terms-of-service`.
- Moved `Contact.tsx` ➝ `app/contact/page.tsx`
- Refactored the component to match page-style syntax
- Verified `/contact` route works correctly
- Removed old file from `components`
Resolves #41
> refactor: move contact.tsx to app/contact/page.tsx for route consistency

- src/components/ui/Navbar.tsx
- Closes #15
- Replaces temporary gradient placeholder with official website logo
Implemented the website logo in the navbar as requested in #15:
- Removed the temporary gradient placeholder logo
- Added the official `icon.png` logo with proper Next.js Image optimization
- Maintained all existing navbar functionality
- Ensured proper sizing and quality settings
- **Added:**
- Official logo image (`app/icon.png`)
- **Modified:**
- `Navbar.tsx` to display the logo
- Removed commented-out gradient placeholder code
- **Optimized:**
- Used Next.js Image component with quality=90
- Added proper alt text for accessibility
- Logo is properly optimized through Next.js Image component
- Maintained all existing scroll functionality
- Verified responsive behavior
- Followed Next.js best practices for …
> feat: Add logo on homepage

- package-lock.json
- package.json
- src/app/layout.tsx
- src/components/CTASection.tsx
- src/components/home/hero.tsx
- src/components/theme-provider.tsx
- src/components/ui/Navbar.tsx
- src/components/ui/switch.tsx
This PR addresses Issue #47  by introducing a fully functional dark mode to the ShadowChat landing page. The implementation ensures that users can seamlessly switch between light and dark themes, enhancing the user experience, especially in low-light environments.
- **Dark Mode Theme**: Developed a dark mode variant of the landing page, adhering closely to the design specifications provided in the Figma file.
- **Toggle Functionality**: Added a toggle button located at the top-right corner of the page, allowing users to switch between light and dark modes effortlessly.
- **Responsive Design**: Ensured that the dark mode is fully responsive and functions correctly across various devices and screen sizes.
- **Styling**: Utilized CSS variables to manage theme colors, enabling easy …
> feat: Implement the Dark Mode of Landing Page

- DESIGN-LINK.md
> FIX: Added a link to the design file

- package.json
- src/app/authentication/page.tsx
- src/components/WalletModal.tsx
- src/components/ui/dialog.tsx
Close #49 
https://github.com/user-attachments/assets/98194818-bb4e-4355-b44c-0ee49f5f6f81
> feat: Add Connect Wallet button and selection modal

- contracts/GroupChat.cairo
- package-lock.json
- tests/test_group_chat.cairo
> Add functionality to create chat groups in contract

- contract/src/lib.cairo
- contract/src/message.cairo
- contract/tests/test_contract.cairo
- contract/tests/test_message.cairo
This PR implements the `edit_message` functionality
Though currently there are various security holes in the contract, as anybody can call any of those functions and perform actions
I also adjusted code to build and ensure it tests.
One test for the edit success was written, and it passes
This PR Closes #88
> feat: edit_message and tests.

- contract/src/lib.cairo
- contract/src/message.cairo
- contract/tests/test_contract.cairo
- contract/tests/test_message.cairo
cairo_Implementation_of_message_deletion_system closes #87 
- Added message delete system
- Wrote comprehensive unit testss
- Ensured consistency between main contract logic and test setup.
#87 
- [ ✅] ✨ Feature Implementation 
- [ ✅] 🛠 I have tested these changes. 
- [ ✅] 🎨 This PR follows the project's coding style. 
- [✅ ] 🧪 I have added necessary tests (). 
NIL
> feat: Implementation_of_message_deletion_system_#87

- .github/workflows/ci.yml
This PR implements the requested GitHub workflow file for testing and checking linting of all contracts as specified in the issue.
closes #93 
I've created a  workflow that runs all the required commands
```
- `scarb build`
- `scarb test` 
- `scarb fmt --check` 
```
This implementation ensures all contracts are properly tested and linted in our CI pipeline, maintaining code quality standards across the project.
> Contract Testing and Linting

- package.json
- pnpm-lock.yaml
- src/app/layout.tsx
- src/components/WalletModal.tsx
- src/components/ui/toast.tsx
Added toast notification functionality
closes #99
> Toast-Notification-#99

- profile_contract/README.md
- profile_contract/user_profile_nft.cairo
> ERC-1155 NFT Contract for User Profiles

- package.json
- pnpm-lock.yaml
- src/components/external-link/index.tsx
- src/components/footer/page.tsx
📐 Features
✅ ExternalLink component was created
✅ Social media icons are responsive and have a hover, improving the user experience.
✅ Social media icons respond to the dark/light theme
✅ ExtenalLink opens external links, preventing new pages from accessing the original page through window.opener, which is an important security measure.
**close:** https://github.com/SudiptaPaul-31/ShadowChat/issues/114
**Additional notes**
The code is clean, well-commented, and follows best practice conventions.
**Test:**
https://github.com/user-attachments/assets/0da33618-c6e7-49c5-b8af-ab6ea140fc9e
> Feat 114/add socials in footer section

- package-lock.json
- src/components/home/hero.tsx
- src/components/ui/Navbar.tsx
As per the image i remove the Join Waitlist button and also change the Get Early Access button to Get Started. Also, when user clicks on the new Get Started button it should redirect user to the /authentication page so that user can add their respective wallet.
> Fix: added router for the btn and remove a btn

- src/app/authentication/page.tsx
- src/components/StarknetProvider.tsx
- src/components/WalletErrorBoundary.tsx
- src/components/WalletLoader.tsx
- src/components/WalletModal.tsx
- src/components/anonymous-profile/wallet-card.tsx
- src/context/WalletContext.tsx
- Implement global wallet context for state management
- Store connection state in sessionStorage for persistence
- Remove duplicate wallet connection logic from individual pages
- Handle wallet events (account changes, disconnections)
- Ensure single wallet connection flow across the application
Closes #[127]
> Fix: Persist wallet connection across page navigation #127
